//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG.Sonarr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MG.Sonarr.Resources.ExMessages", typeof(ExMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer is too small to be used as a copy destination. Expected minimum length: {0}, Received length: {1}.
        /// </summary>
        public static string Buffer_TooSmall {
            get {
                return ResourceManager.GetString("Buffer_TooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection must contain at least one element..
        /// </summary>
        public static string Collections_ExpectedOneOrMore {
            get {
                return ResourceManager.GetString("Collections_ExpectedOneOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element in the array/span is null and was guarded against..
        /// </summary>
        public static string Collections_ItemIsNull {
            get {
                return ResourceManager.GetString("Collections_ItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;null&gt;.
        /// </summary>
        public static string Null_AsString {
            get {
                return ResourceManager.GetString("Null_AsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cast the value to the specified type -&gt; {0}.
        /// </summary>
        public static string Reflection_CannotCastToType {
            get {
                return ResourceManager.GetString("Reflection_CannotCastToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is neither of the types expected. Expected: &apos;{0}&apos; or &apos;{1}&apos;, Received: &apos;{2}&apos;.
        /// </summary>
        public static string Reflection_ExpectedEitherType_2 {
            get {
                return ResourceManager.GetString("Reflection_ExpectedEitherType_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not of the expected type. Expected: &apos;{0}&apos;, Received: &apos;{1}&apos;.
        /// </summary>
        public static string Reflection_ExpectedExactlyType {
            get {
                return ResourceManager.GetString("Reflection_ExpectedExactlyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not the exact or a derivative of the expected type. Expected: &apos;{0]&apos;, Received: &apos;{1}&apos;.
        /// </summary>
        public static string Reflection_ExpectedTypeOrDerivative {
            get {
                return ResourceManager.GetString("Reflection_ExpectedTypeOrDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured during the PoshSonarr module initialization..
        /// </summary>
        public static string Startup_Exception_DefaultMessage {
            get {
                return ResourceManager.GetString("Startup_Exception_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something catastrophic happened in the JSON options setup routine. No JSON converters for the various SonarrObjects could be found/created. JSON serialization/deserialization will not function correctly without them. We can&apos;t let the module continue :(.
        /// </summary>
        public static string Startup_Exception_NoConvertersConstructed {
            get {
                return ResourceManager.GetString("Startup_Exception_NoConvertersConstructed", resourceCulture);
            }
        }
    }
}
