//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG.Sonarr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MG.Sonarr.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Response (size in bytes: {0}) -&gt; {1}.
        /// </summary>
        public static string Debug_JSONResponse_Preamble {
            get {
                return ResourceManager.GetString("Debug_JSONResponse_Preamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string Timer_Unit_Milliseconds {
            get {
                return ResourceManager.GetString("Timer_Unit_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string Timer_Unit_Seconds {
            get {
                return ResourceManager.GetString("Timer_Unit_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received response -&gt; {0} ({1}).
        /// </summary>
        public static string Verbose_ReceivedResponse_Format {
            get {
                return ResourceManager.GetString("Verbose_ReceivedResponse_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received response after {0} - {1} ({2}).
        /// </summary>
        public static string Verbose_ReceivedResponse_Timed_Format {
            get {
                return ResourceManager.GetString("Verbose_ReceivedResponse_Timed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending {0} request -&gt; {1}.
        /// </summary>
        public static string Verbose_SendingRequest_Format {
            get {
                return ResourceManager.GetString("Verbose_SendingRequest_Format", resourceCulture);
            }
        }
    }
}
